module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      "url-text": "#b3b3b3",
      "url-hover": "#ffffff",
      "sidebar-background": "#000000",
      "home-background": "#121212",
      "sidebar-selected": "#282828",
      base: "#fafafa",
      white: "#ffffff",
      "close-red-fill": "#fc605c",
      "minimize-yellow-fill": "#fdbc40",
      "fullscreen-green-fill": "#34c749",
      "close-red-outline": "#df4845",
      "minimize-yellow-outline": "#dfa034",
      "fullscreen-green-outline": "#34af42",
      "title-bar-background": "#1f1f1f",
      searchbar: "#f5f5f5",
      "searchbar-text": "#000000",
      "song-title": "#ffffff",
      "song-artist": "#b3b3b3",
      duration: "#b3b3b3",
      "top-result-bg": "#181818",
      "hover-song-bg": "#282828",
      "secondary-icon-fill": "#848FA5",
      "hover-song-image-bg": "#000000",
      "soundbar-background": "#181818",
      "soundbar-fill": "#535353",
      "soundbar-progress": "#b3b3b3",
      "soundbar-thumb": "#ffffff",
      "soundbar-time-text": "#b3b3b3",
    },
    fontFamily: {
      roboto: ["'Roboto'", "sans-serif"],
    },
    extend: {
      spacing: {
        "title-bar": "2.5rem",
        "song-image": "2.5rem",
      },
      padding: {
        4: "1rem",
      },
    },
    fontSize: {
      xxs: "0.775rem",
      "4xl": "2.25rem",
      sm: ".875rem",
      "2xl": "1.5rem",
      smaller: "0.95rem",
    },
  },
  plugins: [],
};
